"""APEX FastAPI package: app construction, models, state, and routers."""

from __future__ import annotations

from core.api.app import _app_lifespan, app, get_allowed_origins, main
from core.api.assistant import (
    _execute_agent_turn,
    _resolve_cloud_profile_status,
    _resolve_local_profile_status,
    _trim_agent_history,
    build_agent_profile_statuses as _build_agent_profile_statuses,
    query_agent,
    unload_active_local_model_endpoint,
)
from core.api.briefing import (
    _DEMO_STAGE_DELAY_SECONDS,
    _compute_confidence_and_failures,
    _evaluate_sports_trust,
    _run_demo_briefing,
    _split_sports_report,
    trigger_briefing,
)
from core.api.demo import (
    _validate_mock_agent_response,
    build_demo_briefing as _build_demo_briefing,
    load_mock_agent_responses as _load_mock_agent_responses,
    load_mock_telemetry as _load_mock_telemetry,
    mock_briefing_history as _mock_briefing_history,
    run_demo_agent_query as _run_demo_agent_query,
)
from core.api.models import (
    AgentProfileStatus,
    BriefingHistoryRecord,
    BriefingResponse,
    CreateReminderRequest,
    CreateReminderResponse,
    DigestPayload,
    LocalLoadedModelStatus,
    LocalUnloadResponse,
    MarketResponse,
    MarketTickerItem,
    MarkReadRequest,
    MarkReadResponse,
    PipelineStatusSnapshot,
    PipelineSynthesisState,
    ReminderRecord,
    RuntimeMetadata,
    TelemetryPayload,
    parse_digest_payload as _parse_digest_payload,
    parse_runtime_metadata as _parse_runtime_metadata,
)
from core.api.state import (
    PipelineState,
    _TRIGGER_LOCK,
    _speak_and_cleanup,
    global_pipeline_state,
)
from core.api.routers.briefings import get_briefing_history
from core.api.routers.assistant import list_agent_profiles
from core.api.routers.market import get_market_snapshot
from core.api.routers.reminders import (
    create_reminder,
    list_unread_reminders,
    mark_reminders_read,
)
from core.api.routers.system import (
    _build_settings_response,
    get_global_config,
    get_pipeline_diagnostic_status,
    get_runtime_settings,
    get_system_diagnostics,
    health_check,
    patch_runtime_settings,
)
from core.api.tts import clean_for_tts, resolve_tts_diagnostics as _resolve_tts_diagnostics

__all__ = [
    "AgentProfileStatus",
    "BriefingHistoryRecord",
    "BriefingResponse",
    "CreateReminderRequest",
    "CreateReminderResponse",
    "DigestPayload",
    "LocalLoadedModelStatus",
    "LocalUnloadResponse",
    "MarketResponse",
    "MarketTickerItem",
    "MarkReadRequest",
    "MarkReadResponse",
    "PipelineState",
    "PipelineStatusSnapshot",
    "PipelineSynthesisState",
    "ReminderRecord",
    "RuntimeMetadata",
    "TelemetryPayload",
    "_DEMO_STAGE_DELAY_SECONDS",
    "_TRIGGER_LOCK",
    "_app_lifespan",
    "_build_agent_profile_statuses",
    "_build_demo_briefing",
    "_build_settings_response",
    "_compute_confidence_and_failures",
    "_evaluate_sports_trust",
    "_execute_agent_turn",
    "_load_mock_agent_responses",
    "_load_mock_telemetry",
    "_mock_briefing_history",
    "_parse_digest_payload",
    "_parse_runtime_metadata",
    "_resolve_cloud_profile_status",
    "_resolve_local_profile_status",
    "_resolve_tts_diagnostics",
    "_run_demo_agent_query",
    "_run_demo_briefing",
    "_speak_and_cleanup",
    "_split_sports_report",
    "_trim_agent_history",
    "_validate_mock_agent_response",
    "app",
    "clean_for_tts",
    "create_reminder",
    "get_allowed_origins",
    "get_briefing_history",
    "get_global_config",
    "get_market_snapshot",
    "get_pipeline_diagnostic_status",
    "get_runtime_settings",
    "get_system_diagnostics",
    "global_pipeline_state",
    "health_check",
    "list_agent_profiles",
    "list_unread_reminders",
    "main",
    "mark_reminders_read",
    "patch_runtime_settings",
    "query_agent",
    "trigger_briefing",
    "unload_active_local_model_endpoint",
]
