"""Runtime settings foundation: models, normalize, and process-wide store."""

from __future__ import annotations

from core.settings.models import (
    SETTINGS_SCHEMA_VERSION,
    AgentSettingsPatch,
    AgentSettings,
    BriefingPatch,
    BriefingSettings,
    FeaturesPatch,
    FeaturesSettings,
    LlamaCppPatch,
    LlamaCppSettings,
    LlamaCppServerStatusResponse,
    ModulesPatch,
    ModulesSettings,
    McpPatch,
    McpServerEnablementPatch,
    McpServerEnablementSettings,
    McpServersPatch,
    McpServersSettings,
    McpSettings,
    RuntimeSettingsSnapshot,
    SettingsPatch,
    SettingsResponse,
    ToolProfile,
    ToolProfilesPatch,
    ToolProfilesSettings,
    VoicePatch,
    VoiceSettings,
)
from core.settings.store import (
    RuntimeSettingsStore,
    SettingsPersistenceError,
    get_settings_store,
    reset_settings_store_for_tests,
)

__all__ = [
    "SETTINGS_SCHEMA_VERSION",
    "AgentSettingsPatch",
    "AgentSettings",
    "BriefingPatch",
    "BriefingSettings",
    "FeaturesPatch",
    "FeaturesSettings",
    "LlamaCppPatch",
    "LlamaCppSettings",
    "LlamaCppServerStatusResponse",
    "ModulesPatch",
    "ModulesSettings",
    "McpPatch",
    "McpServerEnablementPatch",
    "McpServerEnablementSettings",
    "McpServersPatch",
    "McpServersSettings",
    "McpSettings",
    "RuntimeSettingsSnapshot",
    "RuntimeSettingsStore",
    "SettingsPatch",
    "SettingsPersistenceError",
    "SettingsResponse",
    "ToolProfile",
    "ToolProfilesPatch",
    "ToolProfilesSettings",
    "VoicePatch",
    "VoiceSettings",
    "get_settings_store",
    "reset_settings_store_for_tests",
]
