export const API_BASE = 'http://127.0.0.1:8000'

export const API_ENDPOINTS = {
  cortexLocalModelLoad: `${API_BASE}/api/v1/cortex/local-model/load`,
  cortexLocalModelUnload: `${API_BASE}/api/v1/cortex/local-model/unload`,
  cortexToolCatalog: (agent: string) =>
    `${API_BASE}/api/v1/cortex/tool-catalog?agent=${encodeURIComponent(agent)}`,
  cortexToolPreflight: `${API_BASE}/api/v1/cortex/tool-preflight`,
  cortexToolProfiles: `${API_BASE}/api/v1/cortex/tool-profiles`,
  cortexToolProfile: (profileId: string) =>
    `${API_BASE}/api/v1/cortex/tool-profiles/${encodeURIComponent(profileId)}`,
  cortexToolProfileDefault: `${API_BASE}/api/v1/cortex/tool-profiles/default`,
  agents: `${API_BASE}/api/v1/agents`,
  agentVerify: (agent: string) => `${API_BASE}/api/v1/agents/${encodeURIComponent(agent)}/verify`,
  cortexConversations: `${API_BASE}/api/v1/cortex/conversations`,
  cortexConversation: (conversationId: string) => `${API_BASE}/api/v1/cortex/conversations/${encodeURIComponent(conversationId)}`,
  cortexConversationTurns: (conversationId: string) => `${API_BASE}/api/v1/cortex/conversations/${encodeURIComponent(conversationId)}/turns`,
  cortexContext: `${API_BASE}/api/v1/cortex/context`,
  cortexContextRecord: (recordId: string) => `${API_BASE}/api/v1/cortex/context/${encodeURIComponent(recordId)}`,
  cortexContextEntities: `${API_BASE}/api/v1/cortex/context/entities`,
  cortexContextCapture: `${API_BASE}/api/v1/cortex/context/captures`,
  cortexContextActions: `${API_BASE}/api/v1/cortex/context/actions`,
  cortexRetrievalStatus: `${API_BASE}/api/v1/cortex/retrieval/status`,
  cortexRetrievalPrepare: `${API_BASE}/api/v1/cortex/retrieval/prepare`,
  actions: `${API_BASE}/api/v1/actions`,
  action: (actionId: string) => `${API_BASE}/api/v1/actions/${encodeURIComponent(actionId)}`,
  actionApprove: (actionId: string) => `${API_BASE}/api/v1/actions/${encodeURIComponent(actionId)}/approve`,
  actionReject: (actionId: string) => `${API_BASE}/api/v1/actions/${encodeURIComponent(actionId)}/reject`,
  actionVerify: (actionId: string) => `${API_BASE}/api/v1/actions/${encodeURIComponent(actionId)}/verify`,
  briefingHistory: `${API_BASE}/api/v1/briefings/history`,
  briefingTargets: `${API_BASE}/api/v1/briefings/targets`,
  briefingsGenerate: `${API_BASE}/api/v1/briefings/generate`,
  config: `${API_BASE}/api/v1/config`,
  diagnostics: `${API_BASE}/api/v1/diagnostics`,
  market: `${API_BASE}/api/v1/market`,
  mcpStatus: `${API_BASE}/api/v1/mcp/status`,
  llamaCppStatus: `${API_BASE}/api/v1/llama-cpp/status`,
  microsoftTodoStatus: `${API_BASE}/api/v1/microsoft-todo/status`,
  microsoftTodoLists: `${API_BASE}/api/v1/microsoft-todo/lists`,
  microsoftTodoAuthStart: `${API_BASE}/api/v1/microsoft-todo/auth/start`,
  microsoftTodoAuth: `${API_BASE}/api/v1/microsoft-todo/auth`,
  preflight: `${API_BASE}/api/v1/preflight`,
  reminders: `${API_BASE}/api/v1/reminders`,
  reminderTask: (id: string) => `${API_BASE}/api/v1/reminders/task?id=${encodeURIComponent(id)}`,
  remindersCompleted: `${API_BASE}/api/v1/reminders/completed`,
  remindersComplete: `${API_BASE}/api/v1/reminders/complete`,
  remindersUpdate: `${API_BASE}/api/v1/reminders/update`,
  remindersDelete: `${API_BASE}/api/v1/reminders/delete`,
  remindersReopen: `${API_BASE}/api/v1/reminders/reopen`,
  remindersSync: `${API_BASE}/api/v1/reminders/sync`,
  remindersDismiss: `${API_BASE}/api/v1/reminders/dismiss`,
  settings: `${API_BASE}/api/v1/settings`,
  status: `${API_BASE}/api/v1/status`,
  telemetryLatest: `${API_BASE}/api/v1/telemetry/latest`,
  telemetryRefresh: `${API_BASE}/api/v1/telemetry/refresh`,
  trigger: `${API_BASE}/api/v1/trigger`,
  voiceSpeak: `${API_BASE}/api/v1/voice/speak`,
} as const
