export const API_BASE = 'http://127.0.0.1:8000'

export const API_ENDPOINTS = {
  cortexLocalModelLoad: `${API_BASE}/api/v1/cortex/local-model/load`,
  cortexLocalModelUnload: `${API_BASE}/api/v1/cortex/local-model/unload`,
  cortexToolScopes: `${API_BASE}/api/v1/cortex/tool-scopes`,
  agents: `${API_BASE}/api/v1/agents`,
  agentVerify: (agent: string) => `${API_BASE}/api/v1/agents/${encodeURIComponent(agent)}/verify`,
  cortexQuery: `${API_BASE}/api/v1/cortex/query`,
  briefingHistory: `${API_BASE}/api/v1/briefings/history`,
  briefingsGenerate: `${API_BASE}/api/v1/briefings/generate`,
  config: `${API_BASE}/api/v1/config`,
  diagnostics: `${API_BASE}/api/v1/diagnostics`,
  market: `${API_BASE}/api/v1/market`,
  mcpStatus: `${API_BASE}/api/v1/mcp/status`,
  llamaCppStatus: `${API_BASE}/api/v1/llama-cpp/status`,
  microsoftTodoStatus: `${API_BASE}/api/v1/microsoft-todo/status`,
  microsoftTodoAuthStart: `${API_BASE}/api/v1/microsoft-todo/auth/start`,
  microsoftTodoAuth: `${API_BASE}/api/v1/microsoft-todo/auth`,
  preflight: `${API_BASE}/api/v1/preflight`,
  reminders: `${API_BASE}/api/v1/reminders`,
  remindersRead: `${API_BASE}/api/v1/reminders/read`,
  settings: `${API_BASE}/api/v1/settings`,
  status: `${API_BASE}/api/v1/status`,
  telemetryLatest: `${API_BASE}/api/v1/telemetry/latest`,
  telemetryRefresh: `${API_BASE}/api/v1/telemetry/refresh`,
  trigger: `${API_BASE}/api/v1/trigger`,
  voiceSpeak: `${API_BASE}/api/v1/voice/speak`,
} as const
