from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


class ToolCall(BaseModel):
    id: str = Field(description="Unique call identifier provided by the model.")
    name: str = Field(description="The matching name of the tool to execute.")
    arguments: Dict[str, Any] = Field(
        description="Arguments mapping validated against the tool schema."
    )
    thought_signature: Optional[str] = Field(
        default=None,
        description="Opaque reasoning token required to maintain Gemini 3 loop state.",
    )


class ToolResult(BaseModel):
    id: str = Field(description="The unique identifier corresponding to the ToolCall.")
    name: str = Field(description="The name of the tool executed.")
    output: Any = Field(
        description="Serializable raw outputs returned from the Python handler."
    )


class AgentMessage(BaseModel):
    role: Literal["user", "model", "tool"] = Field(
        description="Message role in the chat history."
    )
    content: Optional[str] = Field(
        default=None, description="Raw text payload from user or assistant."
    )
    tool_calls: Optional[List[ToolCall]] = Field(
        default=None, description="Tool requests generated by the model."
    )
    tool_results: Optional[List[ToolResult]] = Field(
        default=None, description="Tool execution results returned to the model."
    )


class AgentQueryRequest(BaseModel):
    prompt: str = Field(description="The user's direct operations query.")
    profile: Literal[
        "comet", "nova", "pulsar", "lynx", "acinonyx", "neofelis"
    ] = Field(
        default="comet",
        description="The APEX agent role tier (cloud or local Ollama profile).",
    )
    session_id: Optional[str] = Field(
        default=None, description="Optional temporary session grouping identifier."
    )
    history: List[AgentMessage] = Field(
        default_factory=list,
        description="Recent conversation history for the session.",
    )
    snapshot_id: Optional[str] = Field(
        default=None,
        description=(
            "Optional telemetry snapshot ID. When present and matching the "
            "current in-memory snapshot, module display text is injected as "
            "HUD context. Absent or mismatched IDs inject no snapshot context."
        ),
    )
    briefing_id: Optional[int] = Field(
        default=None,
        ge=1,
        description=(
            "Optional briefing history row ID. When present, that briefing's "
            "prose and insights are injected as HUD context. Absent IDs inject "
            "no briefing context."
        ),
    )


class AgentQueryResponse(BaseModel):
    answer: str = Field(description="The final synthesized response from the agent.")
    profile_used: Dict[str, Any] = Field(
        description="Display details of the configured profile used."
    )
    tool_trace: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Audit trace of tools called during the loop.",
    )
    tool_outputs: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Structured outputs of whitelisted tools executed.",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Active temporary session grouping identifier.",
    )
    error: Optional[str] = Field(
        default=None, description="Detailed error diagnostics, if any."
    )
